'''
kw: allot
re_str: (?<![a-z])allot(?![a-z])
kw: almost
re_str: (?<![a-z])almost(?![a-z])
kw: alot
re_str: (?<![a-z])alot(?![a-z])
kw: ambigu
re_str: (?<![a-z])[A-Z]?ambigu[A-Z]?(?![a-z])
kw: any
re_str: (?<![a-z])any(?![a-z])
kw: anybod
re_str: (?<![a-z])[A-Z]?anybod[A-Z]?(?![a-z])
kw: anyhow
re_str: (?<![a-z])anyhow(?![a-z])
kw: anyone
re_str: (?<![a-z])[A-Z]?anyone[A-Z]?(?![a-z])
kw: anything
re_str: (?<![a-z])anything(?![a-z])
kw: anytime
re_str: (?<![a-z])anytime(?![a-z])
kw: anywhere
re_str: (?<![a-z])anywhere(?![a-z])
kw: apparently
re_str: (?<![a-z])apparently(?![a-z])
kw: appear
re_str: (?<![a-z])appear(?![a-z])
kw: appeared
re_str: (?<![a-z])appeared(?![a-z])
kw: appearing
re_str: (?<![a-z])appearing(?![a-z])
kw: appears
re_str: (?<![a-z])appears(?![a-z])
kw: approximat
re_str: (?<![a-z])[A-Z]?approximat[A-Z]?(?![a-z])
kw: arbitrar
re_str: (?<![a-z])[A-Z]?arbitrar[A-Z]?(?![a-z])
kw: assum
re_str: (?<![a-z])[A-Z]?assum[A-Z]?(?![a-z])
kw: barely
re_str: (?<![a-z])barely(?![a-z])
kw: bet
re_str: (?<![a-z])bet(?![a-z])
kw: bets
re_str: (?<![a-z])bets(?![a-z])
kw: betting
re_str: (?<![a-z])betting(?![a-z])
kw: blur
re_str: (?<![a-z])[A-Z]?blur[A-Z]?(?![a-z])
kw: borderline
re_str: (?<![a-z])[A-Z]?borderline[A-Z]?(?![a-z])
kw: chance
re_str: (?<![a-z])chance(?![a-z])
kw: confus
re_str: (?<![a-z])[A-Z]?confus[A-Z]?(?![a-z])
kw: contingen
re_str: (?<![a-z])[A-Z]?contingen[A-Z]?(?![a-z])
kw: depend
re_str: (?<![a-z])depend(?![a-z])
kw: depended
re_str: (?<![a-z])depended(?![a-z])
kw: depending
re_str: (?<![a-z])depending(?![a-z])
kw: depends
re_str: (?<![a-z])depends(?![a-z])
kw: disorient
re_str: (?<![a-z])[A-Z]?disorient[A-Z]?(?![a-z])
kw: doubt
re_str: (?<![a-z])[A-Z]?doubt[A-Z]?(?![a-z])
kw: dubious
re_str: (?<![a-z])[A-Z]?dubious[A-Z]?(?![a-z])
kw: dunno
re_str: (?<![a-z])dunno(?![a-z])
kw: fairly
re_str: (?<![a-z])fairly(?![a-z])
kw: fuzz
re_str: (?<![a-z])[A-Z]?fuzz[A-Z]?(?![a-z])
kw: generally
re_str: (?<![a-z])generally(?![a-z])
kw: guess
re_str: (?<![a-z])guess(?![a-z])
kw: guessed
re_str: (?<![a-z])guessed(?![a-z])
kw: guesses
re_str: (?<![a-z])guesses(?![a-z])
kw: guessing
re_str: (?<![a-z])guessing(?![a-z])
kw: halfass
re_str: (?<![a-z])[A-Z]?halfass[A-Z]?(?![a-z])
kw: hardly
re_str: (?<![a-z])hardly(?![a-z])
kw: hazie
re_str: (?<![a-z])[A-Z]?hazie[A-Z]?(?![a-z])
kw: hazy
re_str: (?<![a-z])hazy(?![a-z])
kw: hesita
re_str: (?<![a-z])[A-Z]?hesita[A-Z]?(?![a-z])
kw: hope
re_str: (?<![a-z])hope(?![a-z])
kw: hoped
re_str: (?<![a-z])hoped(?![a-z])
kw: hopeful
re_str: (?<![a-z])hopeful(?![a-z])
kw: hopefully
re_str: (?<![a-z])hopefully(?![a-z])
kw: hopefulness
re_str: (?<![a-z])hopefulness(?![a-z])
kw: hopes
re_str: (?<![a-z])hopes(?![a-z])
kw: hoping
re_str: (?<![a-z])hoping(?![a-z])
kw: hypothes
re_str: (?<![a-z])[A-Z]?hypothes[A-Z]?(?![a-z])
kw: hypothetic
re_str: (?<![a-z])[A-Z]?hypothetic[A-Z]?(?![a-z])
kw: incomplet
re_str: (?<![a-z])[A-Z]?incomplet[A-Z]?(?![a-z])
kw: indecis
re_str: (?<![a-z])[A-Z]?indecis[A-Z]?(?![a-z])
kw: indefinit
re_str: (?<![a-z])[A-Z]?indefinit[A-Z]?(?![a-z])
kw: indetermin
re_str: (?<![a-z])[A-Z]?indetermin[A-Z]?(?![a-z])
kw: indirect
re_str: (?<![a-z])[A-Z]?indirect[A-Z]?(?![a-z])
kw: kind(of)
re_str: (?<![a-z])kind(of)(?![a-z])
kw: kinda
re_str: (?<![a-z])kinda(?![a-z])
kw: kindof
re_str: (?<![a-z])kindof(?![a-z])
kw: likel
re_str: (?<![a-z])[A-Z]?likel[A-Z]?(?![a-z])
kw: lot
re_str: (?<![a-z])lot(?![a-z])
kw: lotof
re_str: (?<![a-z])lotof(?![a-z])
kw: lots
re_str: (?<![a-z])lots(?![a-z])
kw: lotsa
re_str: (?<![a-z])lotsa(?![a-z])
kw: lotta
re_str: (?<![a-z])lotta(?![a-z])
kw: luck
re_str: (?<![a-z])luck(?![a-z])
kw: lucked
re_str: (?<![a-z])lucked(?![a-z])
kw: lucki
re_str: (?<![a-z])[A-Z]?lucki[A-Z]?(?![a-z])
kw: luckless
re_str: (?<![a-z])[A-Z]?luckless[A-Z]?(?![a-z])
kw: lucks
re_str: (?<![a-z])lucks(?![a-z])
kw: lucky
re_str: (?<![a-z])lucky(?![a-z])
kw: mainly
re_str: (?<![a-z])mainly(?![a-z])
kw: marginal
re_str: (?<![a-z])[A-Z]?marginal[A-Z]?(?![a-z])
kw: may
re_str: (?<![a-z])may(?![a-z])
kw: maybe
re_str: (?<![a-z])maybe(?![a-z])
kw: might
re_str: (?<![a-z])might(?![a-z])
kw: mightve
re_str: (?<![a-z])mightve(?![a-z])
kw: might've
re_str: (?<![a-z])might've(?![a-z])
kw: most
re_str: (?<![a-z])most(?![a-z])
kw: mostly
re_str: (?<![a-z])mostly(?![a-z])
kw: myster
re_str: (?<![a-z])[A-Z]?myster[A-Z]?(?![a-z])
kw: nearly
re_str: (?<![a-z])nearly(?![a-z])
kw: obscur
re_str: (?<![a-z])[A-Z]?obscur[A-Z]?(?![a-z])
kw: occasional
re_str: (?<![a-z])[A-Z]?occasional[A-Z]?(?![a-z])
kw: often
re_str: (?<![a-z])often(?![a-z])
kw: opinion
re_str: (?<![a-z])opinion(?![a-z])
kw: option
re_str: (?<![a-z])option(?![a-z])
kw: overall
re_str: (?<![a-z])overall(?![a-z])
kw: partly
re_str: (?<![a-z])partly(?![a-z])
kw: perhaps
re_str: (?<![a-z])perhaps(?![a-z])
kw: possib
re_str: (?<![a-z])[A-Z]?possib[A-Z]?(?![a-z])
kw: practically
re_str: (?<![a-z])practically(?![a-z])
kw: pretty
re_str: (?<![a-z])pretty(?![a-z])
kw: probable
re_str: (?<![a-z])probable(?![a-z])
kw: probablistic
re_str: (?<![a-z])[A-Z]?probablistic[A-Z]?(?![a-z])
kw: probably
re_str: (?<![a-z])probably(?![a-z])
kw: puzzl
re_str: (?<![a-z])[A-Z]?puzzl[A-Z]?(?![a-z])
kw: question
re_str: (?<![a-z])[A-Z]?question[A-Z]?(?![a-z])
kw: quite
re_str: (?<![a-z])quite(?![a-z])
kw: random
re_str: (?<![a-z])[A-Z]?random[A-Z]?(?![a-z])
kw: seem
re_str: (?<![a-z])seem(?![a-z])
kw: seemed
re_str: (?<![a-z])seemed(?![a-z])
kw: seeming
re_str: (?<![a-z])[A-Z]?seeming[A-Z]?(?![a-z])
kw: seems
re_str: (?<![a-z])seems(?![a-z])
kw: shaki
re_str: (?<![a-z])[A-Z]?shaki[A-Z]?(?![a-z])
kw: shaky
re_str: (?<![a-z])shaky(?![a-z])
kw: some
re_str: (?<![a-z])some(?![a-z])
kw: somebod
re_str: (?<![a-z])[A-Z]?somebod[A-Z]?(?![a-z])
kw: somehow
re_str: (?<![a-z])somehow(?![a-z])
kw: someone
re_str: (?<![a-z])[A-Z]?someone[A-Z]?(?![a-z])
kw: something
re_str: (?<![a-z])[A-Z]?something[A-Z]?(?![a-z])
kw: sometime
re_str: (?<![a-z])sometime(?![a-z])
kw: sometimes
re_str: (?<![a-z])sometimes(?![a-z])
kw: somewhat
re_str: (?<![a-z])somewhat(?![a-z])
kw: sort
re_str: (?<![a-z])sort(?![a-z])
kw: sorta
re_str: (?<![a-z])sorta(?![a-z])
kw: sortof
re_str: (?<![a-z])sortof(?![a-z])
kw: sorts
re_str: (?<![a-z])sorts(?![a-z])
kw: sortsa
re_str: (?<![a-z])sortsa(?![a-z])
kw: spose
re_str: (?<![a-z])spose(?![a-z])
kw: suppose
re_str: (?<![a-z])suppose(?![a-z])
kw: supposed
re_str: (?<![a-z])supposed(?![a-z])
kw: supposes
re_str: (?<![a-z])supposes(?![a-z])
kw: supposing
re_str: (?<![a-z])supposing(?![a-z])
kw: supposition
re_str: (?<![a-z])[A-Z]?supposition[A-Z]?(?![a-z])
kw: tempora
re_str: (?<![a-z])[A-Z]?tempora[A-Z]?(?![a-z])
kw: tentativ
re_str: (?<![a-z])[A-Z]?tentativ[A-Z]?(?![a-z])
kw: theor
re_str: (?<![a-z])[A-Z]?theor[A-Z]?(?![a-z])
kw: typically
re_str: (?<![a-z])typically(?![a-z])
kw: uncertain
re_str: (?<![a-z])[A-Z]?uncertain[A-Z]?(?![a-z])
kw: unclear
re_str: (?<![a-z])[A-Z]?unclear[A-Z]?(?![a-z])
kw: undecided
re_str: (?<![a-z])[A-Z]?undecided[A-Z]?(?![a-z])
kw: undetermin
re_str: (?<![a-z])[A-Z]?undetermin[A-Z]?(?![a-z])
kw: unknow
re_str: (?<![a-z])[A-Z]?unknow[A-Z]?(?![a-z])
kw: unlikel
re_str: (?<![a-z])[A-Z]?unlikel[A-Z]?(?![a-z])
kw: unluck
re_str: (?<![a-z])[A-Z]?unluck[A-Z]?(?![a-z])
kw: unresolv
re_str: (?<![a-z])[A-Z]?unresolv[A-Z]?(?![a-z])
kw: unsettl
re_str: (?<![a-z])[A-Z]?unsettl[A-Z]?(?![a-z])
kw: unsure
re_str: (?<![a-z])[A-Z]?unsure[A-Z]?(?![a-z])
kw: usually
re_str: (?<![a-z])usually(?![a-z])
kw: vague
re_str: (?<![a-z])[A-Z]?vague[A-Z]?(?![a-z])
kw: variab
re_str: (?<![a-z])[A-Z]?variab[A-Z]?(?![a-z])
kw: varies
re_str: (?<![a-z])varies(?![a-z])
kw: vary
re_str: (?<![a-z])vary(?![a-z])
kw: wonder
re_str: (?<![a-z])wonder(?![a-z])
kw: wondered
re_str: (?<![a-z])wondered(?![a-z])
kw: wondering
re_str: (?<![a-z])wondering(?![a-z])
kw: wonders
re_str: (?<![a-z])wonders(?![a-z])
kw: absolute
re_str: (?<![a-z])absolute(?![a-z])
kw: absolutely
re_str: (?<![a-z])absolutely(?![a-z])
kw: accura
re_str: (?<![a-z])[A-Z]?accura[A-Z]?(?![a-z])
kw: all
re_str: (?<![a-z])all(?![a-z])
kw: altogether
re_str: (?<![a-z])altogether(?![a-z])
kw: always
re_str: (?<![a-z])always(?![a-z])
kw: apparent
re_str: (?<![a-z])apparent(?![a-z])
kw: assur
re_str: (?<![a-z])[A-Z]?assur[A-Z]?(?![a-z])
kw: blatant
re_str: (?<![a-z])[A-Z]?blatant[A-Z]?(?![a-z])
kw: certain
re_str: (?<![a-z])[A-Z]?certain[A-Z]?(?![a-z])
kw: clear
re_str: (?<![a-z])clear(?![a-z])
kw: clearly
re_str: (?<![a-z])clearly(?![a-z])
kw: commit
re_str: (?<![a-z])commit(?![a-z])
kw: commitment
re_str: (?<![a-z])[A-Z]?commitment[A-Z]?(?![a-z])
kw: commits
re_str: (?<![a-z])commits(?![a-z])
kw: committ
re_str: (?<![a-z])[A-Z]?committ[A-Z]?(?![a-z])
kw: complete
re_str: (?<![a-z])complete(?![a-z])
kw: completed
re_str: (?<![a-z])completed(?![a-z])
kw: completely
re_str: (?<![a-z])completely(?![a-z])
kw: completes
re_str: (?<![a-z])completes(?![a-z])
kw: confidence
re_str: (?<![a-z])confidence(?![a-z])
kw: confident
re_str: (?<![a-z])confident(?![a-z])
kw: confidently
re_str: (?<![a-z])confidently(?![a-z])
kw: correct
re_str: (?<![a-z])[A-Z]?correct[A-Z]?(?![a-z])
kw: defined
re_str: (?<![a-z])defined(?![a-z])
kw: definite
re_str: (?<![a-z])definite(?![a-z])
kw: definitely
re_str: (?<![a-z])definitely(?![a-z])
kw: definitive
re_str: (?<![a-z])[A-Z]?definitive[A-Z]?(?![a-z])
kw: directly
re_str: (?<![a-z])directly(?![a-z])
kw: distinct
re_str: (?<![a-z])[A-Z]?distinct[A-Z]?(?![a-z])
kw: entire
re_str: (?<![a-z])[A-Z]?entire[A-Z]?(?![a-z])
kw: essential
re_str: (?<![a-z])essential(?![a-z])
kw: ever
re_str: (?<![a-z])ever(?![a-z])
kw: every
re_str: (?<![a-z])every(?![a-z])
kw: everybod
re_str: (?<![a-z])[A-Z]?everybod[A-Z]?(?![a-z])
kw: everything
re_str: (?<![a-z])[A-Z]?everything[A-Z]?(?![a-z])
kw: evident
re_str: (?<![a-z])[A-Z]?evident[A-Z]?(?![a-z])
kw: exact
re_str: (?<![a-z])[A-Z]?exact[A-Z]?(?![a-z])
kw: explicit
re_str: (?<![a-z])[A-Z]?explicit[A-Z]?(?![a-z])
kw: extremely
re_str: (?<![a-z])extremely(?![a-z])
kw: fact
re_str: (?<![a-z])fact(?![a-z])
kw: facts
re_str: (?<![a-z])facts(?![a-z])
kw: factual
re_str: (?<![a-z])[A-Z]?factual[A-Z]?(?![a-z])
kw: forever
re_str: (?<![a-z])forever(?![a-z])
kw: frankly
re_str: (?<![a-z])frankly(?![a-z])
kw: fundamental
re_str: (?<![a-z])fundamental(?![a-z])
kw: fundamentalis
re_str: (?<![a-z])[A-Z]?fundamentalis[A-Z]?(?![a-z])
kw: fundamentally
re_str: (?<![a-z])fundamentally(?![a-z])
kw: fundamentals
re_str: (?<![a-z])fundamentals(?![a-z])
kw: guarant
re_str: (?<![a-z])[A-Z]?guarant[A-Z]?(?![a-z])
kw: implicit
re_str: (?<![a-z])[A-Z]?implicit[A-Z]?(?![a-z])
kw: indeed
re_str: (?<![a-z])indeed(?![a-z])
kw: inevitab
re_str: (?<![a-z])[A-Z]?inevitab[A-Z]?(?![a-z])
kw: infallib
re_str: (?<![a-z])[A-Z]?infallib[A-Z]?(?![a-z])
kw: invariab
re_str: (?<![a-z])[A-Z]?invariab[A-Z]?(?![a-z])
kw: irrefu
re_str: (?<![a-z])[A-Z]?irrefu[A-Z]?(?![a-z])
kw: must
re_str: (?<![a-z])must(?![a-z])
kw: mustnt
re_str: (?<![a-z])mustnt(?![a-z])
kw: mustn't
re_str: (?<![a-z])mustn't(?![a-z])
kw: must'nt
re_str: (?<![a-z])must'nt(?![a-z])
kw: mustve
re_str: (?<![a-z])mustve(?![a-z])
kw: must've
re_str: (?<![a-z])must've(?![a-z])
kw: necessar
re_str: (?<![a-z])[A-Z]?necessar[A-Z]?(?![a-z])
kw: never
re_str: (?<![a-z])never(?![a-z])
kw: obvious
re_str: (?<![a-z])[A-Z]?obvious[A-Z]?(?![a-z])
kw: perfect
re_str: (?<![a-z])[A-Z]?perfect[A-Z]?(?![a-z])
kw: positiv
re_str: (?<![a-z])[A-Z]?positiv[A-Z]?(?![a-z])
kw: precis
re_str: (?<![a-z])[A-Z]?precis[A-Z]?(?![a-z])
kw: proof
re_str: (?<![a-z])proof(?![a-z])
kw: prove
re_str: (?<![a-z])[A-Z]?prove[A-Z]?(?![a-z])
kw: pure
re_str: (?<![a-z])[A-Z]?pure[A-Z]?(?![a-z])
kw: sure
re_str: (?<![a-z])[A-Z]?sure[A-Z]?(?![a-z])
kw: total
re_str: (?<![a-z])total(?![a-z])
kw: totally
re_str: (?<![a-z])totally(?![a-z])
kw: true
re_str: (?<![a-z])true(?![a-z])
kw: truest
re_str: (?<![a-z])truest(?![a-z])
kw: truly
re_str: (?<![a-z])truly(?![a-z])
kw: truth
re_str: (?<![a-z])[A-Z]?truth[A-Z]?(?![a-z])
kw: unambigu
re_str: (?<![a-z])[A-Z]?unambigu[A-Z]?(?![a-z])
kw: undeniab
re_str: (?<![a-z])[A-Z]?undeniab[A-Z]?(?![a-z])
kw: undoubt
re_str: (?<![a-z])[A-Z]?undoubt[A-Z]?(?![a-z])
kw: unquestion
re_str: (?<![a-z])[A-Z]?unquestion[A-Z]?(?![a-z])
kw: wholly
re_str: (?<![a-z])wholly(?![a-z])
'''